Repository Nishino0719/ReportToken, pull requests merged in 2020-09, with the labels that each got.

#21 IPFSへのファイルのアップロード＋ハッシュ値の取得 #4
  package-lock.json
  package.json
  pages/uploadPage.vue
  plugins/ipfs.js
Labels: develop

#26 #20,#25 purchseTokenの実装
  build/contracts/Address.json
  build/contracts/Context.json
  build/contracts/ERC20.json
  build/contracts/IERC20.json
  build/contracts/Migrations.json
  build/contracts/ReportToken.json
  build/contracts/SafeMath.json
  contracts/ReportToken.sol
  migrations/2_ReportToken_initialSupply.js
  migrations/ReportToken_initialSupply.js
  truffle-config.js
Labels: develop, fix

#36 レポートのハッシュ値を格納、取得するスマートコントラクトの作成 #27
  build/contracts/Address.json
  build/contracts/Context.json
  build/contracts/ERC20.json
  build/contracts/IERC20.json
  build/contracts/Migrations.json
  build/contracts/ReportInfo.json
  build/contracts/ReportToken.json
  build/contracts/SafeMath.json
  contracts/ReportInfo.sol
  migrations/3_ReportInfo.js
Labels: dependencies

#39 Firebaseとの接続　#34
  nuxt.config.js
  package-lock.json
  package.json
  pages/walletPage.vue
  plugins/firebase.js
Labels: dependencies
