Repository Nishino0719/ReportToken, pull requests merged in 2020-11, with the labels that each got.

#76 UIの調整　#74
  assets/images/reportoken-logo_header.png
  assets/images/reportoken-logo_header1.png
  assets/images/top-view.png
  assets/styles/reset.css
  components/filecard.vue
  components/filecards.vue
  components/footer.vue
  components/header.vue
  components/tutorial.vue
  components/upload.vue
  pages/folders/_id.vue
  pages/homePage.vue
  pages/index.vue
  pages/serchPage.vue
  pages/tutorialPage.vue
  pages/uploadPage.vue
  pages/walletPage.vue
Labels: Front

#80 レポートカードをよりレポートの見た目に近づけました *75
  components/filecard.vue
  components/folder.vue
  components/header.vue
  pages/folders/_id.vue
  pages/myPage.vue
  pages/uploadPage.vue
Labels: Front, dependencies

#82 RP関数を年２回定期実行させる #65
  .firebaserc
  firebase.json
  functions/.gitignore
  functions/index.js
  functions/package.json
  pages/index.vue
  plugins/firebase.js
Labels: algorithm, fix

#86 walletの送信のUI/UXの実装 #73
  assets/styles/reset.css
  pages/myPage.vue
Labels: dependencies

#87 レポート購入機能、検索機能の実装とその他不具合修正 #30 #72 #77 #78 #83
  assets/styles/reset.css
  components/filecard.vue
  components/footer.vue
  pages/folders/_id.vue
  pages/index.vue
  pages/myPage.vue
  pages/serchPage.vue
  pages/uploadPage.vue
Labels: Front, dependencies, fix

#92 購入したレポートをマイページで表示　#91 #89
  components/header.vue
  pages/folders/_id.vue
  pages/myPage.vue
  pages/uploadPage.vue
Labels: bug, dependencies, develop

#94 #93 addressへのパースを実装
  contracts/Algorithm.sol
  contracts/ReportToken.sol
  functions/index.js
  migrations/4_Algorithm.js
Labels: develop

#97 自分が共有したレポート、購入したレポートが見れないバグを解消
  functions/index.js
  pages/folders/_id.vue
  pages/myPage.vue
  pages/uploadPage.vue
  plugins/web3.js
Labels: bug
